Create Bluetooth permission checker universal
SoftTeco/AndroidBLE pull request #10
Opened 2023-12-12 16:27 UTC by AlexJustUser

## Summary

Creating a universal permission checker class.

## Reasons

Necessary for quickly checking permissions on Android devices.

## References

closes #5

2023-12-19 21:07 UTC, EvgeniyFilippov requested changes

2023-12-19 21:07 UTC, EvgeniyFilippov commented on app/src/main/kotlin/com/softteco/template/utils/BluetoothPermissionCheckerImpl.kt
> +        return hasPermission
Here is a simpler option:
```kotlin
val permissionsToCheck = when {
            Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> PERMISSIONS_FOR_BLUETOOTH_AFTER_ANDROID_12
            else -> PERMISSIONS_FOR_BLUETOOTH_BEFORE_ANDROID_12
        }

        return permissionsToCheck.all {
            requestPermission(activity, it, permissionsToCheck)
        }
```

2023-12-19 21:07 UTC, EvgeniyFilippov commented on app/src/main/kotlin/com/softteco/template/utils/BluetoothPermissionCheckerImpl.kt
> +            else -> true
it is better not to use **"!!"**
Here is a safer and simpler option:
```kotlin
return bluetoothAdapter != null &&
                activity.packageManager?.hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE) == true
```

2024-01-03 13:10 UTC, EvgeniyFilippov approved these changes

2024-01-09 09:39 UTC, bstolyarov commented
1. Could you check all @SuppressLint("MissingPermission") if they need. 
2. Could you check if the app has permissions in all places where @SuppressLint("MissingPermission") is used? 
3. Can we minimize using @SuppressLint("MissingPermission") by replacing it with @RequiresPermission to postpone checking? 
4. @EvgeniyFilippov Could you mark as resolved all resolved conversations

2024-01-16 15:56 UTC, bstolyarov approved these changes

2024-01-16 15:59 UTC, merged