Bluetooth functionality
SoftTeco/AndroidBLE pull request #40
Opened 2024-07-17 10:17 UTC by AlexJustUser

https://github.com/user-attachments/assets/8a36887c-759c-4681-8ecf-36b9c121090b

## Summary

Added support for saving Bluetooth connections in the background.
Added support for connecting to multiple Bluetooth devices simultaneously.
Created a universal interface for Bluetooth devices with the ability to expand the list of supported devices.
Added functionality for displaying real data from the device on charts.

## Reasons

Integration with peripheral smart home sensors.

## References

closes #12 
closes #13 
closes #14 
closes #15

2024-07-18 22:00 UTC, EvgeniyFilippov approved these changes

2024-07-18 22:00 UTC, EvgeniyFilippov commented on app/src/main/kotlin/com/softteco/template/data/device/ThermometerData.kt
> +    val deviceId: UUID = UUID.randomUUID(),
@pcfaktor  left such a comment in my pr: "Can an object of this class be used without deviceId or deviceName? Are default values for these fields really necessary?"

2024-07-26 07:41 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/data/base/ProfileDataBase.kt
> +package com.softteco.template.data.base
I think the place for this file and the `dao` and `model` packages is in the `device` package. This package is meant to be the package for the basic (generic) entities of the data layer

2024-07-26 07:49 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/data/base/ProfileDataBase.kt
> +                .allowMainThreadQueries()
Can't we avoid this?

2024-07-26 11:31 UTC, pcfaktor requested changes

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/data/bluetooth/usecase/DeviceSaveUseCase.kt
> +class DeviceSaveUseCase @Inject constructor(
Is there any advantage to using UserCases this way? When it just bypasses the repository method call?

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/utils/bluetooth/DevicesCacheStoreImpl.kt
> +class DevicesCacheStoreImpl @Inject constructor(private val devicesDao: DevicesDao) :
It looks like a repository implementation. If so, the `util` package is not the right place for it.

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/utils/bluetooth/DevicesDataCacheStoreImpl.kt
> +class DevicesDataCacheStoreImpl @Inject constructor(private val thermometerDataDao: ThermometerDataDao) :
Same comment as for `DevicesCacheStoreImpl`

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/res/values/strings.xml
> +    <string name="bluetooth_icon_description">Baseline_bluetooth_24</string>
These two are not used. If they were intended to be used as contentDescripton, then:
widgets such as ImageViews and ImageButtons should use the contentDescription attribute to specify a textual description of the widget so that screen readers and other accessibility tools can adequately describe the user interface

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/home/device/connection/manual/ManualSelectionViewModel.kt
> +            SupportedDevice(
Since we have already implemented support for a specific device, we can create a final list of supported devices and put it there. For example:
```
.Device.kt

data class SupportedDevice(
    val type: Device.Type,
    val family: Device.Family,
    val model: Device.Model,
    val img: String,
)

enum class SupportedDevices(val description: SupportedDevice) {
    LYWSD03MMC(
        SupportedDevice(
            Device.Type.TemperatureAndHumidity,
            Device.Family.Sensor,
            Device.Model.LYWSD03MMC,
            "file:///android_asset/icon/temperature_monitor.webp"
        )
    )
}

```

2024-07-26 11:31 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothScreen.kt
> +    val deviceName = stringResource(R.string.temperature_and_humidity_LYWSD03MMC)
A hard-coded name is given here. If the screen displays devices of a specific model, we can retrieve it from an object already in ViewModel:

`var filteredName: String = SupportedDevices.LYWSD03MMC.description.model.nameRes`.

If the screen can be reused (probably) for other device types, it is better to pass the model as a navigation argument. As we do with `DEVICE_ID_KEY` for Dashboard screens.

2024-07-26 11:52 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothScreen.kt
> +        viewModel.onScanCallback {
Maybe we can wrap these calls into a single public fn in the ViewModel?

2024-07-26 12:35 UTC, pcfaktor requested changes

2024-07-26 12:35 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothScreen.kt
> +        onFilter,
We can just:
`onFilter = { checked -> viewModel.setFiltered(checked) },`

2024-07-26 12:35 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothScreen.kt
> +    var checked by remember { mutableStateOf(true) }
Maybe consider storing the state of the switch in the state of the screen?

2024-07-26 12:35 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothScreen.kt
> +        devices.forEach { device ->
We can just:
`items(devices) { device ->...}`

2024-07-26 12:35 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/bluetooth/BluetoothViewModel.kt
> +                _devices.value =
We can simplify this:
```
                _devices.value = _bluetoothDevices
                    .map { it.value.device }
                    .filter { device ->
                        if (filtered) getBluetoothDeviceName(device) == filteredName else true
                    }
```

2024-08-07 13:51 UTC, AlexJustUser commented on app/src/main/res/values/strings.xml
> +    <string name="bluetooth_icon_description">Baseline_bluetooth_24</string>
The second value has been removed as unused. The first is used for the connection service in the background.

2024-08-07 13:58 UTC, AlexJustUser commented on app/src/main/kotlin/com/softteco/template/data/bluetooth/usecase/DeviceSaveUseCase.kt
> +class DeviceSaveUseCase @Inject constructor(
This change was added for further use of usecases outside the repository.

2024-08-08 13:06 UTC, pcfaktor approved these changes
Good job!

2024-08-08 13:13 UTC, merged